// Claude Code adapter (RF-ADP-01/02/05/06, RF-GEN-05/06, RF-ORQ-10, RF-DOM-02)
// and the git safety net (RF-VER-03..06).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { FIXTURES, run, snapshot, git, write } from './fixtures.js';
import { findSecrets, addedLines } from '../src/guards/checks.js';
import { ADAPTERS } from '../src/generate/index.js';

const read = (root, p) => fs.readFileSync(path.join(root, p), 'utf8');
const frontmatter = (text) => Object.fromEntries([...text.matchAll(/^(\w[\w-]*): (.*)$/gm)].map((m) => [m[1], m[2]]));

test('RF-ADP-01 / RF-GEN-04: one subagent per needed role, with its tools and model tier', async (t) => {
  const root = FIXTURES.monorepo(t);
  assert.equal((await run(['init', '--yes'], { cwd: root })).code, 0);
  const agents = fs.readdirSync(path.join(root, '.claude/agents')).sort();
  assert.deepEqual(agents, ['architect.md', 'backend-dev.md', 'debugger.md', 'doc-writer.md', 'frontend-dev.md', 'qa-tester.md', 'reviewer.md', 'spec-reviewer.md']);
  const reviewer = frontmatter(read(root, '.claude/agents/reviewer.md'));
  assert.deepEqual([reviewer.name, reviewer.tools, reviewer.model], ['reviewer', 'Read, Grep, Glob, Bash', 'opus']);
  assert.equal(frontmatter(read(root, '.claude/agents/doc-writer.md')).model, 'haiku');
  assert.equal(frontmatter(read(root, '.claude/agents/frontend-dev.md')).model, 'sonnet');
  // RF-DOM-02: read-only roles cannot edit.
  for (const role of ['spec-reviewer', 'reviewer', 'debugger']) assert.doesNotMatch(frontmatter(read(root, `.claude/agents/${role}.md`)).tools, /Write|Edit/);
  assert.match(read(root, '.claude/agents/frontend-dev.md'), /You may write only in: `apps\/web\/\*\*`/);

  const front = FIXTURES.frontend(t);
  await run(['init', '--yes'], { cwd: front });
  assert.ok(!fs.existsSync(path.join(front, '.claude/agents/backend-dev.md')));
});

test('RF-ADP-05 / RF-ORQ-10: models and tiers are configurable per tool and role', async (t) => {
  const root = FIXTURES.frontend(t);
  await run(['init', '--yes'], { cwd: root });
  fs.appendFileSync(path.join(root, 'harness.config.yaml'), 'models:\n  claude-code: {high: claude-opus-5-5, mid: claude-sonnet-5-5, low: claude-haiku-4-5}\nroles:\n  reviewer: {tier: mid}\n');
  assert.equal((await run(['sync', '--yes'], { cwd: root })).code, 0);
  assert.equal(frontmatter(read(root, '.claude/agents/reviewer.md')).model, 'claude-sonnet-5-5');
  assert.equal(frontmatter(read(root, '.claude/agents/architect.md')).model, 'claude-opus-5-5');
});

test('RF-ADP-01: the /sdd:* commands, the approve/reject answers and the skills', async (t) => {
  const root = FIXTURES.frontend(t);
  await run(['init', '--yes'], { cwd: root });
  const cmds = fs.readdirSync(path.join(root, '.claude/commands/sdd')).map((f) => f.replace('.md', '')).sort();
  assert.deepEqual(cmds, ['approve', 'change', 'clarify', 'commit', 'constitution', 'next', 'plan', 'reject', 'spec', 'status', 'tasks', 'validate']);
  assert.match(read(root, '.claude/commands/sdd/next.md'), /^---\ndescription: Run exactly one task/);
  // RF-GEN-05/06: canonical skills and identical copies for Claude Code.
  for (const s of ['sdd-orchestrator', 'spec-generator', 'triage-report', 'adr']) {
    const canonical = read(root, `.agents/skills/${s}/SKILL.md`);
    assert.equal(read(root, `.claude/skills/${s}/SKILL.md`), canonical, s);
    assert.match(canonical, new RegExp(`^---\\nname: ${s}\\ndescription: .+\\n---\\n<!-- Generated by sdd-harness`));
  }
  const manifest = JSON.parse(read(root, '.harness/manifest.lock'));
  assert.ok(manifest.entries.some((e) => e.path === '.claude/skills/adr/SKILL.md' && /^[0-9a-f]{64}$/.test(e.hash)));
});

test('RF-ADP-02 / RF-MRG-02: permissions and hooks are merged into existing settings and removed cleanly', async (t) => {
  const root = FIXTURES.existingConfig(t);
  write(root, {
    '.claude/settings.json': {
      model: 'opus',
      permissions: { allow: ['Bash(npm test:*)'], deny: ['Read(.env)'] },
      hooks: { PreToolUse: [{ matcher: 'Bash', hooks: [{ type: 'command', command: 'echo team-hook' }] }] },
    },
  });
  git(root, 'add', '-A');
  git(root, '-c', 'core.hooksPath=.git/no-hooks', 'commit', '-qm', 'chore: claude settings');
  const before = snapshot(root);
  assert.equal((await run(['init', '--yes', '--mode', 'team'], { cwd: root })).code, 0);
  const s = JSON.parse(read(root, '.claude/settings.json'));
  assert.equal(s.model, 'opus');
  assert.deepEqual(s.permissions.allow, ['Bash(npm test:*)']);
  assert.equal(s.permissions.deny[0], 'Read(.env)');
  assert.ok(s.permissions.deny.includes('Bash(git push:*)'));
  assert.ok(s.permissions.ask.includes('Bash(npm install:*)'));
  assert.equal(s.hooks.PreToolUse[0].hooks[0].command, 'echo team-hook');
  assert.match(s.hooks.PreToolUse[1].hooks[0].command, /hook\.js" PreToolUse$/);
  for (const e of ['PostToolUse', 'UserPromptSubmit', 'SessionStart', 'SessionEnd', 'Stop']) assert.ok(s.hooks[e], e);
  assert.equal((await run(['sync', '--yes'], { cwd: root })).stdout.includes('Nothing to change'), true);
  assert.equal((await run(['remove', '--yes'], { cwd: root })).code, 0);
  assert.deepEqual(snapshot(root), before);
});

test('the generated hook really runs from .harness/scripts (ES modules, any cwd)', async (t) => {
  const root = FIXTURES.frontend(t);
  await run(['init', '--yes'], { cwd: root });
  const settings = JSON.parse(read(root, '.claude/settings.local.json'));
  const command = settings.hooks.PreToolUse.at(-1).hooks[0].command;
  assert.equal(command, 'node "$CLAUDE_PROJECT_DIR/.harness/scripts/hook.js" PreToolUse');
  const payload = JSON.stringify({ session_id: 'x', cwd: root, hook_event_name: 'PreToolUse', tool_name: 'Bash', tool_input: { command: 'git push' } });
  const r = spawnSync(process.execPath, [path.join(root, '.harness/scripts/hook.js'), 'PreToolUse'], { input: payload, encoding: 'utf8', cwd: path.join(root, 'src'), env: { ...process.env, HARNESS_LANG: 'en', CLAUDE_PROJECT_DIR: root } });
  assert.equal(r.status, 2, r.stderr);
  assert.match(r.stderr, /Committing is the user's job/);
  const ok = spawnSync(process.execPath, [path.join(root, '.harness/scripts/hook.js'), 'PreToolUse'], { input: payload.replace('git push', 'git status'), encoding: 'utf8', env: { ...process.env, CLAUDE_PROJECT_DIR: root } });
  assert.equal(ok.status, 0, ok.stderr);
  const sdd = spawnSync(process.execPath, [path.join(root, '.harness/scripts/sdd.js'), 'status'], { encoding: 'utf8', cwd: root, env: { ...process.env, HARNESS_LANG: 'en' } });
  assert.equal(sdd.status, 0, sdd.stderr);
  assert.match(sdd.stdout, /Active spec: —/);
});

test('RF-ADP-06: adapters are registered without touching the core', () => {
  const a = ADAPTERS['claude-code'];
  assert.equal(a.id, 'claude-code');
  assert.equal(typeof a.generate, 'function');
  assert.deepEqual(a.RULES, ['commits', 'deps', 'protected', 'docs', 'retries', 'verify', 'lanes']);
});

test('RF-VER-03/04: the pre-commit hook blocks secrets, stray docs and failing checks; the user can still commit', async (t) => {
  const root = FIXTURES.frontend(t);
  // Quick checks run lint and typecheck: make them real commands for the test.
  // "type": "module" as in many real projects: the extensionless hook must still run (found in the real Claude Code test).
  write(root, { 'package.json': { name: 'shop-web', type: 'module', scripts: { lint: 'node -e "process.exit(require(\'fs\').existsSync(\'lint.fail\') ? 1 : 0)"', test: 'node -e ""' } } });
  git(root, 'add', '-A');
  git(root, 'commit', '-qm', 'chore: scripts');
  assert.equal((await run(['init', '--yes'], { cwd: root })).code, 0);
  assert.equal(git(root, 'config', 'core.hooksPath').trim(), '.harness/githooks');

  const commit = () => spawnSync('git', ['-c', 'user.email=a@b.c', '-c', 'user.name=U', 'commit', '-qm', 'feat: x'], { cwd: root, encoding: 'utf8' });
  // Built at run time so no key-shaped literal lives in the repository.
  write(root, { 'src/config.ts': `export const apiKey = "${'sk-' + 'ant-api03-'}abcdefghijklmnopqrstuvwxyz0123";\n` });
  git(root, 'add', 'src/config.ts');
  let r = commit();
  assert.notEqual(r.status, 0);
  assert.match(r.stderr, /secrets: possible Anthropic key in src\/config\.ts/);

  git(root, 'reset', '-q', 'src/config.ts');
  fs.rmSync(path.join(root, 'src/config.ts'));
  write(root, { 'NOTES.md': '# notes\n', 'src/a.ts': 'export {};\n', 'lint.fail': '' });
  git(root, 'add', 'NOTES.md', 'src/a.ts');
  r = commit();
  assert.match(r.stderr, /docs: NOTES\.md is not in the documentation whitelist/);
  assert.match(r.stderr, /verify: shop-web → npm run lint failed/);

  git(root, 'reset', '-q', 'NOTES.md');
  fs.rmSync(path.join(root, 'lint.fail'));
  r = commit();
  assert.equal(r.status, 0, r.stderr);
});

test('RF-VER-05: an existing hooks manager is chained (team) or left alone with instructions (local)', async (t) => {
  const team = FIXTURES.existingConfig(t);
  await run(['init', '--yes', '--mode', 'team'], { cwd: team });
  assert.equal(read(team, '.husky/pre-commit'), 'npm test\n\n# harness:begin\nnode .harness/scripts/checks.js pre-commit\n# harness:end\n');
  assert.equal(git(team, 'config', 'core.hooksPath').trim(), '.husky');
  const local = FIXTURES.existingConfig(t);
  const r = await run(['init', '--yes'], { cwd: local });
  assert.match(r.stdout, /already uses husky for git hooks.*node \.harness\/scripts\/checks\.js pre-commit/);
  assert.equal(read(local, '.husky/pre-commit'), 'npm test\n');
});

test('RF-VER-06: CI template on request, only when the scripts are committed', async (t) => {
  const root = FIXTURES.monorepo(t);
  await run(['init', '--yes', '--mode', 'team'], { cwd: root });
  fs.appendFileSync(path.join(root, 'harness.config.yaml'), '');
  const cfg = read(root, 'harness.config.yaml').replace('provider: none', 'provider: github');
  fs.writeFileSync(path.join(root, 'harness.config.yaml'), cfg);
  assert.equal((await run(['sync', '--yes'], { cwd: root })).code, 0);
  const wf = read(root, '.github/workflows/sdd-harness.yml');
  assert.match(wf, /pnpm install --frozen-lockfile/);
  assert.match(wf, /node \.harness\/scripts\/checks\.js ci --range/);
  assert.match(wf, /sdd\.js verify --component api\n {6}- run: node \.harness\/scripts\/sdd\.js verify --component web/);
  const local = FIXTURES.frontend(t);
  await run(['init', '--yes'], { cwd: local });
  fs.writeFileSync(path.join(local, 'harness.config.yaml'), read(local, 'harness.config.yaml').replace('provider: none', 'provider: github'));
  const r = await run(['sync', '--yes'], { cwd: local });
  assert.match(r.stdout, /CI template needs the harness scripts in the repository/);
});

test('secret patterns', () => {
  const diff = '+++ b/a.env.ts\n+const k = "' + 'AKIA' + 'ABCDEFGHIJKLMNOP";\n+const safe = process.env.TOKEN;\n+password: "Xk9pQ2vL8mN4rT6wZ"\n+const label = "password: a b c d e f g h i j k";\n';
  assert.deepEqual(findSecrets(addedLines(diff)).map((h) => h.kind), ['AWS access key', 'secret assignment']);
});
