// harness sync (RF-GEN-09..13, RF-MOD-06, RF-UPG-02, edge cases 7, 8, 24, 25).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import path from 'node:path';
import { FIXTURES, run, snapshot, git } from './fixtures.js';

const file = (root, p) => path.join(root, p);
const read = (root, p) => fs.readFileSync(file(root, p), 'utf8');
const edit = (root, p, fn) => fs.writeFileSync(file(root, p), fn(read(root, p)));

async function activated(t, fixture = 'monorepo', args = []) {
  const root = FIXTURES[fixture](t);
  const r = await run(['init', '--yes', ...args], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  return root;
}

test('RF-GEN-13: two syncs in a row change nothing, byte for byte', async (t) => {
  const root = await activated(t);
  const before = snapshot(root);
  for (let i = 0; i < 2; i += 1) {
    const r = await run(['sync', '--yes'], { cwd: root });
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /Nothing to change/);
  }
  assert.deepEqual(snapshot(root), before);
});

test('RF-GEN-09: a config change is shown as a diff before it is applied', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace('manual_test: task', 'manual_test: story'));
  const declined = await run(['sync'], { cwd: root, answers: { apply: false } });
  assert.equal(declined.code, 1);
  assert.match(declined.stdout, /--- a\/AGENTS\.md\n\+\+\+ b\/AGENTS\.md/);
  // The monorepo fixture documents in Spanish, so the context is in Spanish.
  assert.match(declined.stdout, /-- Tras cada tarea/);
  assert.match(declined.stdout, /\+- Tras cada historia/);
  assert.doesNotMatch(read(root, 'AGENTS.md'), /Tras cada historia/);
  const r = await run(['sync'], { cwd: root, answers: { apply: true } });
  assert.equal(r.code, 0, r.stderr);
  assert.match(read(root, 'AGENTS.md'), /Tras cada historia/);
});

test('RF-GEN-10: sync --dry-run shows the diff and writes nothing', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace('in_scope: 2', 'in_scope: 1'));
  const before = snapshot(root);
  const r = await run(['sync', '--dry-run'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.match(r.stdout, /\+- Como máximo 1 intentos automáticos/);
  assert.match(r.stdout, /"in_scope": 1/);
  assert.match(r.stdout, /Dry run: nothing was written/);
  assert.deepEqual(snapshot(root), before);
});

test('RF-GEN-11: a hand-edited generated file offers keep, overwrite or diff', async (t) => {
  const root = await activated(t);
  edit(root, '.harness/templates/spec.md', (s) => s + '\nmy notes\n');
  edit(root, 'harness.config.yaml', (s) => s.replace('specs: es', 'specs: en'));

  const kept = await run(['sync', '--yes'], { cwd: root });
  assert.equal(kept.code, 0, kept.stderr);
  assert.match(kept.stdout, /\.harness\/templates\/spec\.md was generated by the harness and then modified by hand\. → keep my version/);
  assert.match(read(root, '.harness/templates/spec.md'), /my notes/);
  assert.match(read(root, '.harness/templates/plan.md'), /Test strategy/);

  const choices = ['diff', 'overwrite'];
  const r = await run(['sync'], { cwd: root, answers: { 'conflict:.harness/templates/spec.md': () => choices.shift(), apply: true } });
  assert.equal(r.code, 0, r.stderr);
  assert.match(r.stdout, /\n-my notes\n/, 'the diff (mine → harness) was shown');
  assert.doesNotMatch(read(root, '.harness/templates/spec.md'), /my notes/);
  assert.match(read(root, '.harness/templates/spec.md'), /Functional requirements/);
});

test('RF-GEN-12: sync refuses an invalid configuration', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace('install_mode: local', 'install_mode: shared'));
  const before = snapshot(root);
  const r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 1);
  assert.match(r.stderr, /harness\.config\.yaml:\d+:\d+ {2}install_mode: "shared" is not allowed/);
  assert.deepEqual(snapshot(root), before);
});

test('RF-MOD-06: switching local → team → local migrates the files', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace('install_mode: local', 'install_mode: team'));
  let r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.ok(fs.existsSync(file(root, 'CLAUDE.md')));
  assert.ok(!fs.existsSync(file(root, 'CLAUDE.local.md')));
  assert.ok(fs.existsSync(file(root, '.harness/.gitignore')));
  // Artifacts stay local (the init default in local mode), so only they remain excluded.
  assert.doesNotMatch(read(root, '.git/info/exclude'), /\/\.harness\//);
  assert.match(read(root, '.git/info/exclude'), /\/specs\//);
  assert.match(git(root, 'status', '--porcelain'), /\?\? \.harness\//);

  edit(root, 'harness.config.yaml', (s) => s.replace('install_mode: team', 'install_mode: local'));
  r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.ok(!fs.existsSync(file(root, 'CLAUDE.md')));
  assert.ok(fs.existsSync(file(root, 'CLAUDE.local.md')));
  assert.equal(git(root, 'status', '--porcelain'), '');
});

test('tools added or removed: their files appear and disappear', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace('  - claude-code', '  - codex'));
  const r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.ok(!fs.existsSync(file(root, 'CLAUDE.local.md')));
});

test('edge case 7: a damaged block is reported and left alone', async (t) => {
  const root = await activated(t);
  edit(root, 'AGENTS.md', (s) => s.replace('<!-- harness:end -->', ''));
  const damaged = read(root, 'AGENTS.md');
  edit(root, 'harness.config.yaml', (s) => s.replace('manual_test: task', 'manual_test: spec'));
  const r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 1);
  assert.match(r.stderr, /AGENTS\.md: the harness block is damaged/);
  assert.equal(read(root, 'AGENTS.md'), damaged);
});

test('edge case 8: a missing or corrupt manifest is rebuilt from the expected output', async (t) => {
  const root = await activated(t);
  const manifest = read(root, '.harness/manifest.lock');
  fs.rmSync(file(root, '.harness/manifest.lock'));
  let r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.match(r.stdout, /manifest is missing: it will be rebuilt/);
  assert.equal(JSON.parse(read(root, '.harness/manifest.lock')).entries.length, JSON.parse(manifest).entries.length);
  fs.writeFileSync(file(root, '.harness/manifest.lock'), '{ broken');
  r = await run(['sync', '--yes'], { cwd: root });
  assert.match(r.stdout, /manifest is damaged/);
  assert.equal(JSON.parse(read(root, '.harness/manifest.lock')).version, 1);
});

test('edge case 24: changing the mode with hand-edited files asks for each one', async (t) => {
  const root = await activated(t);
  edit(root, 'CLAUDE.local.md', (s) => s.replace('@AGENTS.md', '@AGENTS.md\n@docs/extra.md'));
  edit(root, 'harness.config.yaml', (s) => s.replace('install_mode: local', 'install_mode: team'));
  const r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 0, r.stderr);
  assert.match(r.stdout, /CLAUDE\.local\.md is no longer needed but was modified by hand\. → keep my version/);
  assert.match(read(root, 'CLAUDE.local.md'), /docs\/extra\.md/);
});

test('RF-UPG-02 / edge case 25: version differences are reported, nothing is upgraded', async (t) => {
  const root = await activated(t);
  edit(root, 'harness.config.yaml', (s) => s.replace(/harness_version: .*/, 'harness_version: 9.0.0'));
  let r = await run(['sync', '--yes'], { cwd: root });
  assert.match(r.stderr, /uses harness 9\.0\.0, newer than this CLI/);
  assert.match(read(root, 'harness.config.yaml'), /harness_version: 9\.0\.0/);
  edit(root, 'harness.config.yaml', (s) => s.replace(/harness_version: .*/, 'harness_version: 0.0.1'));
  r = await run(['sync', '--yes'], { cwd: root });
  assert.match(r.stderr, /activated with harness 0\.0\.1.*harness upgrade/);
  assert.match(read(root, 'harness.config.yaml'), /harness_version: 0\.0\.1/);
});

test('sync from a subdirectory works on the project root; outside a project it fails', async (t) => {
  const root = await activated(t);
  const r = await run(['sync', '--yes'], { cwd: path.join(root, 'apps', 'web') });
  assert.equal(r.code, 0, r.stderr);
  const plain = FIXTURES.frontend(t);
  const r2 = await run(['sync'], { cwd: plain });
  assert.equal(r2.code, 1);
  assert.match(r2.stderr, /not activated/);
});

test('edge case 26: sync waits for a running agent session or cancels', async (t) => {
  const root = await activated(t);
  const { touchLock, releaseLock } = await import('../src/guards/state.js');
  touchLock(root, 'agent-session');
  const r = await run(['sync', '--yes'], { cwd: root });
  assert.equal(r.code, 1);
  assert.match(r.stderr, /An agent session \(agent-session\) is running tasks/);
  const declined = await run(['sync'], { cwd: root, answers: { waitLock: false } });
  assert.equal(declined.code, 1);

  const { main } = await import('../src/cli/main.js');
  const { createScriptedPrompter } = await import('../src/cli/prompt.js');
  let stdout = '';
  setTimeout(() => releaseLock(root, 'agent-session'), 150);
  const code = await main(['sync'], {
    stdout: { write: (s) => { stdout += s; } }, stderr: { write() {} }, env: { HARNESS_LANG: 'en' }, cwd: root,
    readStdin: async () => '', prompter: createScriptedPrompter({ waitLock: true, apply: true }), lockPollMs: 20,
  });
  assert.equal(code, 0, stdout);
  assert.match(stdout, /Nothing to change/);
});
