// Content of the shared agent context: root AGENTS.md (RF-GEN-01, RF-CNV-05)
// and one AGENTS.md per component (RF-GEN-03).

import { DEFAULT_DOCS_WHITELIST } from '../guards/project.js';

export const ALWAYS_ROLES = ['spec-reviewer', 'architect', 'qa-tester', 'reviewer', 'debugger', 'doc-writer'];

/** Implementer role for a component kind. `other` (CLI, library…) is non-UI code. */
export function implementerFor(kind) {
  return kind === 'frontend' ? 'frontend-dev' : 'backend-dev';
}

const joinPath = (base, glob) => (base === '.' || base === '' ? glob : `${base.replace(/\/$/, '')}/${glob}`);

/** The architect writes specs and ADRs, in every repository that owns specs (RF-TOP-02). */
function architectWrites(config) {
  const out = ['specs/**', 'docs/decisions/**'];
  if (config.specs?.location === 'per-repo' && ['multi-repo', 'workspace'].includes(config.topology)) {
    for (const c of Object.values(config.components ?? {})) {
      const dir = String(c.path).replace(/\\/g, '/').replace(/^\.\/?/, '').replace(/\/$/, '');
      if (dir) out.push(`${dir}/specs/**`, `${dir}/docs/decisions/**`);
    }
  }
  return [...new Set(out)];
}

/**
 * RF-GEN-04 / RF-DOM-01: only the roles the project needs, with the paths
 * each one may write.
 */
export function neededRoles(config) {
  const comps = Object.entries(config.components ?? {});
  const writes = new Map();
  for (const [, c] of comps) {
    const role = implementerFor(c.kind ?? 'other');
    if (!writes.has(role)) writes.set(role, []);
    writes.get(role).push(joinPath(c.path, '**'));
  }
  const whitelist = config.docs_whitelist ?? [...DEFAULT_DOCS_WHITELIST];
  const tests = comps.flatMap(([, c]) => [joinPath(c.path, 'tests/**'), joinPath(c.path, 'e2e/**'), joinPath(c.path, '**/*.{test,spec}.*')]);
  const roles = [
    { role: 'spec-reviewer', writes: [] },
    { role: 'architect', writes: architectWrites(config) },
    ...['frontend-dev', 'backend-dev'].filter((r) => writes.has(r)).map((r) => ({ role: r, writes: [...new Set(writes.get(r))] })),
    { role: 'qa-tester', writes: [...new Set(tests)] },
    { role: 'reviewer', writes: [] },
    { role: 'debugger', writes: [] },
    { role: 'doc-writer', writes: whitelist },
  ];
  return roles;
}

const L = {
  en: {
    note: 'Generated by sdd-harness. Do not edit this block: change harness.config.yaml and run `sdd-harness sync`.',
    title: 'Spec-Driven Development (sdd-harness)',
    precedence: 'Precedence',
    precedenceText: (sources) => `When instructions conflict, follow this order: 1) \`docs/constitution.md\`; 2) project conventions: the rest of this file${sources.length ? ` and ${sources.map((s) => `\`${s}\``).join(', ')}` : ''}; 3) sdd-harness skills; 4) third-party skills.`,
    workflow: 'Workflow',
    workflowText: 'Spec → plan and tasks → implementation (frontend and backend in parallel, tests first) → validation, with the documentation always up to date. The sdd skill runs it. The user is asked at two stops only (the spec, and the plan with its tasks) and answers in plain words ("yes", "continue"); the rest moves on and is told in summaries. Templates: `.harness/templates/`.',
    commands: 'Optional shortcuts: `/sdd:status` (what happened), `/sdd:spec`, `/sdd:next`, `/sdd:docs`, `/sdd:review`, `/sdd:validate`, `/sdd:commit`. None is needed to approve or to move on.',
    rules: 'Non-negotiable rules',
    ruleCommit: 'When a story closes, propose the commit (one per repository) and make it if the user says yes. Push, rebase, reset and deleting branches only when the user asks; the tool confirms them.',
    ruleDeps: 'Adding a dependency makes the tool ask the user: say why you need it.',
    ruleProtected: 'A change in a protected zone does not stop the work: record the decision in an ADR draft and tell the user in your summary. Zones:',
    ruleRetries: (n) => `A failing verification gets at most ${n} fix attempts. Then triage (error, reproduction, hypotheses, 2–3 options, recommendation) and the user chooses.`,
    ruleVerify: 'Never report a task as done while lint, typecheck or tests fail.',
    ruleManual: (g) => g === 'none' ? 'No manual test is asked for.' : `After each ${g === 'task' ? 'task' : g === 'story' ? 'user story' : 'spec'}, give manual test instructions (how to start the app, URL or command, steps, test data, expected result per requirement) as a normal question.`,
    ruleDocs: 'Only create documentation files (`.md`, `.mdx`) in:',
    ruleLanes: 'Each role writes only in its own paths (see Roles).',
    ruleHarness: 'Never edit `.harness/` or files generated by the harness. `harness.config.yaml` may change at any moment: the tool asks the user to confirm and the configuration is regenerated on its own.',
    components: 'Components',
    compHeader: '| Component | Path | Stack | Spec prefix | Implemented by | Verification |',
    notConfigured: 'not configured: ask the user before the first task',
    roles: 'Roles',
    readOnly: 'read-only',
    conventions: 'Conventions',
    languages: (l) => `Languages: code ${l.code ?? '?'}, specs ${l.specs ?? '?'}, docs ${l.docs ?? '?'}, commits ${l.commits ?? '?'}, UI ${l.ui ?? '?'}.`,
    commitStyle: (c, note) => (c === 'custom' ? `Commit messages: follow the project convention${note ? ` in \`${note}\`` : ''}.` : c === 'gitmoji' ? 'Commit messages: gitmoji.' : 'Commit messages: Conventional Commits.'),
    style: (s) => `Style and tooling: ${s.join(', ')}.`,
    readBefore: (file, dir) => `Before working in \`${dir}\`, read \`${file}\`.`,
    compTitle: (id) => `Component \`${id}\``,
    compOwner: (role) => `Implemented by: \`${role}\`. Other roles only read here, except \`qa-tester\` in test files.`,
    compPrefix: (p) => `Spec IDs: \`${p}-NNN\`.`,
    compVerify: 'Verification (run from this directory):',
    compStack: (s) => `Stack: ${s || 'not detected'}.`,
  },
  es: {
    note: 'Generado por sdd-harness. No edites este bloque: cambia harness.config.yaml y ejecuta `sdd-harness sync`.',
    title: 'Spec-Driven Development (sdd-harness)',
    precedence: 'Precedencia',
    precedenceText: (sources) => `Si las instrucciones chocan, sigue este orden: 1) \`docs/constitution.md\`; 2) convenciones del proyecto: el resto de este archivo${sources.length ? ` y ${sources.map((s) => `\`${s}\``).join(', ')}` : ''}; 3) skills del harness; 4) skills de terceros.`,
    workflow: 'Flujo',
    workflowText: 'Spec → plan y tareas → implementación (frontend y backend en paralelo, tests primero) → validación, con la documentación siempre al día. Lo dirige la skill sdd. Al usuario solo se le pregunta en dos paradas (la spec, y el plan con sus tareas) y responde hablando ("sí", "continúa"); el resto avanza y se cuenta en los resúmenes. Plantillas: `.harness/templates/`.',
    commands: 'Atajos opcionales: `/sdd:status` (qué pasó), `/sdd:spec`, `/sdd:next`, `/sdd:docs`, `/sdd:review`, `/sdd:validate`, `/sdd:commit`. Ninguno hace falta para aprobar ni para avanzar.',
    rules: 'Reglas innegociables',
    ruleCommit: 'Al cerrar una historia, propón el commit (uno por repositorio) y hazlo si el usuario dice que sí. Push, rebase, reset y borrar ramas solo cuando el usuario lo pida; la herramienta los confirma.',
    ruleDeps: 'Añadir una dependencia hace que la herramienta pregunte al usuario: explica por qué la necesitas.',
    ruleProtected: 'Un cambio en una zona protegida no detiene el trabajo: deja la decisión en un borrador de ADR y cuéntasela al usuario en tu resumen. Zonas:',
    ruleRetries: (n) => `Una verificación que falla tiene como máximo ${n} intentos de corrección. Después, triage (error, reproducción, hipótesis, 2–3 opciones, recomendación) y el usuario elige.`,
    ruleVerify: 'Nunca des una tarea por terminada con lint, tipos o tests fallando.',
    ruleManual: (g) => g === 'none' ? 'No se pide prueba manual.' : `Tras cada ${g === 'task' ? 'tarea' : g === 'story' ? 'historia' : 'spec'}, da instrucciones de prueba manual (cómo arrancar la app, URL o comando, pasos, datos de prueba y resultado esperado por requisito) como una pregunta normal.`,
    ruleDocs: 'Crea archivos de documentación (`.md`, `.mdx`) solo en:',
    ruleLanes: 'Cada rol escribe solo en sus rutas (ver Roles).',
    ruleHarness: 'Nunca edites `.harness/` ni los archivos generados por el harness. `harness.config.yaml` puede cambiar en cualquier momento: la herramienta pide confirmación al usuario y la configuración se regenera sola.',
    components: 'Componentes',
    compHeader: '| Componente | Ruta | Stack | Prefijo de spec | Lo implementa | Verificación |',
    notConfigured: 'sin configurar: pregunta al usuario antes de la primera tarea',
    roles: 'Roles',
    readOnly: 'solo lectura',
    conventions: 'Convenciones',
    languages: (l) => `Idiomas: código ${l.code ?? '?'}, specs ${l.specs ?? '?'}, docs ${l.docs ?? '?'}, commits ${l.commits ?? '?'}, interfaz ${l.ui ?? '?'}.`,
    commitStyle: (c, note) => (c === 'custom' ? `Mensajes de commit: sigue la convención del proyecto${note ? ` en \`${note}\`` : ''}.` : c === 'gitmoji' ? 'Mensajes de commit: gitmoji.' : 'Mensajes de commit: Conventional Commits.'),
    style: (s) => `Estilo y herramientas: ${s.join(', ')}.`,
    readBefore: (file, dir) => `Antes de trabajar en \`${dir}\`, lee \`${file}\`.`,
    compTitle: (id) => `Componente \`${id}\``,
    compOwner: (role) => `Lo implementa: \`${role}\`. El resto de roles solo lee aquí, salvo \`qa-tester\` en los archivos de test.`,
    compPrefix: (p) => `IDs de spec: \`${p}-NNN\`.`,
    compVerify: 'Verificación (ejecutar desde este directorio):',
    compStack: (s) => `Stack: ${s || 'no detectado'}.`,
  },
};

export function contextStrings(lang) {
  return L[lang] ?? L.en;
}

function verifyCell(v, t) {
  const cmds = ['lint', 'typecheck', 'test', 'e2e'].filter((k) => v?.[k]).map((k) => `${k}: \`${v[k]}\``);
  return cmds.length ? cmds.join('<br>') : t.notConfigured;
}

/**
 * @param {object} config
 * @param {{ componentFiles: Record<string, string | null> }} ctx  where each
 *   component's context lives (null when it is covered by the root file)
 */
// Spanish only, whatever the docs language (project rule: no English variants).
const ruleTooling = (globs) => `La configuración de herramientas (${globs.map((g) => `\`${g}\``).join(', ')}) no necesita tarea ni ADR: edítala cuando haga falta (lint, tipos, CI); Claude Code te pedirá confirmación y el usuario decide.`;
const RULE_PROTECTED = 'Zonas protegidas (el harness avisa si las tocas; no las bloquea):';
const RULE_ALERTS = 'El harness no bloquea tu trabajo: te avisa. Si te avisa de una zona protegida, de código sin tarea o fuera de su alcance, sigue, deja la decisión registrada (ADR, tasks.md) y cuéntaselo al usuario en tu resumen. Mantén siempre al día spec, plan, tasks.md y demás documentos que cada cambio afecte.';
const RULE_DOCS_FREE = 'Mantén al día los documentos `.md` que afecte cada cambio (README, CHANGELOG, specs, arquitectura, lecciones): actualizarlos nunca requiere permiso.';
const RULE_MANUAL_NONE = 'No hace falta prueba manual: basta con que la verificación de la tarea pase.';
const RULE_INIT = 'Si ejecutas `/init` o añades instrucciones del proyecto, escríbelas en `AGENTS.md` fuera de este bloque; `CLAUDE.md` solo debe referenciar `@AGENTS.md`.';

export function rootContext(config, ctx) {
  const lang = config.language?.docs ?? 'en';
  const t = contextStrings(lang);
  const whitelist = config.docs_whitelist ?? [...DEFAULT_DOCS_WHITELIST];
  const protectedZones = Object.entries(config.protected ?? {}).filter(([name, globs]) => name !== 'tooling' && globs?.length);
  const tooling = config.protected?.tooling ?? [];
  const comps = Object.entries(config.components ?? {});
  const out = [
    `<!-- ${t.note} -->`,
    `# ${t.title}`,
    '',
    `## ${t.precedence}`,
    '',
    t.precedenceText(config.conventions?.sources ?? []),
    '',
    `## ${t.workflow}`,
    '',
    t.workflowText,
    '',
    t.commands,
    '',
    `## ${t.rules}`,
    '',
    `- ${t.ruleCommit}`,
    `- ${t.ruleDeps}`,
    `- ${RULE_ALERTS}`,
    ...(protectedZones.length ? [`- ${RULE_PROTECTED}`, ...protectedZones.map(([name, globs]) => `  - ${name}: ${globs.map((g) => `\`${g}\``).join(', ')}`)] : []),
    ...(tooling.length ? [`- ${ruleTooling(tooling)}`] : []),
    `- ${t.ruleRetries(config.retries?.in_scope ?? 2)}`,
    `- ${t.ruleVerify}`,
    `- ${config.gates?.manual_test === 'none' ? RULE_MANUAL_NONE : t.ruleManual(config.gates?.manual_test ?? 'story')}`,
    `- ${config.gates?.docs === 'whitelist' ? `${t.ruleDocs} ${whitelist.map((w) => `\`${w}\``).join(', ')}.` : RULE_DOCS_FREE}`,
    `- ${t.ruleLanes}`,
    `- ${t.ruleHarness}`,
    `- ${RULE_INIT}`,
    '',
    `## ${t.components}`,
    '',
    t.compHeader,
    '|---|---|---|---|---|---|',
    ...comps.map(([id, c]) => `| \`${id}\` | \`${c.path}\` | ${c.stack ?? ''} | ${c.id_prefix ?? ''} | \`${implementerFor(c.kind ?? 'other')}\` | ${verifyCell(c.verify, t)} |`),
    '',
    ...comps.flatMap(([id, c]) => {
      const file = ctx.componentFiles?.[id];
      if (!file) return [];
      return [t.readBefore(file, c.path)];
    }),
    `## ${t.roles}`,
    '',
    ...neededRoles(config).map(({ role, writes }) => `- \`${role}\`: ${writes.length ? writes.map((w) => `\`${w}\``).join(', ') : t.readOnly}`),
    '',
    `## ${t.conventions}`,
    '',
    `- ${t.languages(config.language ?? {})}`,
    `- ${t.commitStyle(config.conventions?.commits, config.conventions?.commits_note)}`,
    ...(config.conventions?.style?.length ? [`- ${t.style(config.conventions.style)}`] : []),
  ];
  // Keep a blank line between the component pointers and the next heading.
  return out.join('\n').replace(/\n(## )/g, '\n\n$1').replace(/\n{3,}/g, '\n\n');
}

const STACK_HINTS = {
  en: {
    react: 'React: function components and hooks; keep components small and reuse the design system.',
    next: 'Next.js: respect the router in use (app/ or pages/); server code never reaches the client bundle.',
    vue: 'Vue: single-file components with the Composition API.',
    svelte: 'Svelte: keep components small; stores for shared state.',
    angular: 'Angular: follow the module and service structure already in place.',
    nestjs: 'NestJS: controllers stay thin; logic in services; validate input with DTOs at the edge.',
    express: 'Express: validate input at the edge; errors go through one error handler.',
    fastify: 'Fastify: declare schemas for input and output.',
    django: 'Django: migrations only through the protected-zone gate.',
    fastapi: 'FastAPI: Pydantic models at the edge; dependencies for cross-cutting concerns.',
    prisma: 'Prisma: schema and migrations are a protected zone.',
    postgres: 'PostgreSQL: parameterised queries only; schema changes through migrations.',
    ts: 'TypeScript: no `any` without a reason; the typecheck must pass.',
  },
  es: {
    react: 'React: componentes de función y hooks; componentes pequeños y reutiliza el sistema de diseño.',
    next: 'Next.js: respeta el router en uso (app/ o pages/); el código de servidor nunca llega al bundle del cliente.',
    vue: 'Vue: componentes de un solo archivo con la Composition API.',
    svelte: 'Svelte: componentes pequeños; stores para el estado compartido.',
    angular: 'Angular: sigue la estructura de módulos y servicios existente.',
    nestjs: 'NestJS: controladores finos; la lógica en servicios; valida la entrada con DTOs en el borde.',
    express: 'Express: valida la entrada en el borde; los errores pasan por un único manejador.',
    fastify: 'Fastify: declara esquemas de entrada y salida.',
    django: 'Django: las migraciones solo pasan por el gate de zona protegida.',
    fastapi: 'FastAPI: modelos Pydantic en el borde; dependencias para lo transversal.',
    prisma: 'Prisma: el esquema y las migraciones son zona protegida.',
    postgres: 'PostgreSQL: solo consultas parametrizadas; cambios de esquema mediante migraciones.',
    ts: 'TypeScript: nada de `any` sin motivo; el typecheck debe pasar.',
  },
};

/** RF-GEN-03: context of one component. */
export function componentContext(config, id) {
  const c = config.components[id];
  const lang = config.language?.docs ?? 'en';
  const t = contextStrings(lang);
  const hints = STACK_HINTS[lang] ?? STACK_HINTS.en;
  const parts = String(c.stack ?? '').toLowerCase().split(/[+\s,]+/);
  const verify = ['lint', 'typecheck', 'test', 'e2e'].filter((k) => c.verify?.[k]);
  return [
    `<!-- ${t.note} -->`,
    `# ${t.compTitle(id)}`,
    '',
    `- ${t.compStack(c.stack)}`,
    `- ${t.compOwner(implementerFor(c.kind ?? 'other'))}`,
    ...(c.id_prefix ? [`- ${t.compPrefix(c.id_prefix)}`] : []),
    '',
    t.compVerify,
    '',
    ...(verify.length ? verify.map((k) => `- ${k}: \`${c.verify[k]}\``) : [`- ${t.notConfigured}`]),
    ...(parts.some((p) => hints[p]) ? ['', ...parts.filter((p) => hints[p]).map((p) => `- ${hints[p]}`)] : []),
  ].join('\n');
}
