// Content of the shared agent context: root AGENTS.md (RF-GEN-01, RF-CNV-05)
// and one AGENTS.md per component (RF-GEN-03).

import { DEFAULT_DOCS_WHITELIST } from '../guards/project.js';

export const ALWAYS_ROLES = ['spec-reviewer', 'architect', 'qa-tester', 'reviewer', 'debugger', 'doc-writer'];

/** Implementer role for a component kind. `other` (CLI, library…) is non-UI code. */
export function implementerFor(kind) {
  return kind === 'frontend' ? 'frontend-dev' : 'backend-dev';
}

const joinPath = (base, glob) => (base === '.' || base === '' ? glob : `${base.replace(/\/$/, '')}/${glob}`);

/** The architect writes specs and ADRs, in every repository that owns specs (RF-TOP-02). */
function architectWrites(config) {
  const out = ['specs/**', 'docs/decisions/**'];
  if (['multi-repo', 'workspace'].includes(config.topology)) {
    for (const c of Object.values(config.components ?? {})) {
      const dir = String(c.path).replace(/\\/g, '/').replace(/^\.\/?/, '').replace(/\/$/, '');
      if (dir) out.push(`${dir}/specs/**`, `${dir}/docs/decisions/**`);
    }
  }
  return [...new Set(out)];
}

/**
 * RF-GEN-04 / RF-DOM-01: only the roles the project needs, with the paths
 * each one may write.
 */
export function neededRoles(config) {
  const comps = Object.entries(config.components ?? {});
  const writes = new Map();
  for (const [, c] of comps) {
    const role = implementerFor(c.kind ?? 'other');
    if (!writes.has(role)) writes.set(role, []);
    writes.get(role).push(joinPath(c.path, '**'));
  }
  const whitelist = config.docs_whitelist ?? [...DEFAULT_DOCS_WHITELIST];
  const tests = comps.flatMap(([, c]) => [joinPath(c.path, 'tests/**'), joinPath(c.path, 'e2e/**'), joinPath(c.path, '**/*.{test,spec}.*')]);
  const roles = [
    { role: 'spec-reviewer', writes: [] },
    { role: 'architect', writes: architectWrites(config) },
    ...['frontend-dev', 'backend-dev'].filter((r) => writes.has(r)).map((r) => ({ role: r, writes: [...new Set(writes.get(r))] })),
    { role: 'qa-tester', writes: [...new Set(tests)] },
    { role: 'reviewer', writes: [] },
    { role: 'debugger', writes: [] },
    { role: 'doc-writer', writes: whitelist },
  ];
  return roles;
}

const L = {
  en: {
    note: 'Generated by sdd-harness. Do not edit this block: change harness.config.yaml and run `sdd-harness sync`.',
    title: 'Spec-Driven Development (sdd-harness)',
    precedence: 'Precedence',
    precedenceText: (sources) => `When instructions conflict, follow this order: 1) \`docs/constitution.md\`; 2) project conventions: the rest of this file${sources.length ? ` and ${sources.map((s) => `\`${s}\``).join(', ')}` : ''}; 3) sdd-harness skills; 4) third-party skills.`,
    workflow: 'Workflow',
    workflowText: 'Constitution → spec → clarification → plan → tasks → implementation (one task at a time, tests first) → validation → change (spec first, then code). Never move to the next phase without the user\'s explicit approval. Templates: `.harness/templates/`.',
    commands: 'Commands: `/sdd:constitution`, `/sdd:spec`, `/sdd:clarify`, `/sdd:plan`, `/sdd:tasks`, `/sdd:next`, `/sdd:validate`, `/sdd:change`, `/sdd:status`, `/sdd:commit` (run `sdd-harness doctor` for the syntax of each tool).',
    rules: 'Non-negotiable rules',
    ruleCommit: 'Never run `git commit`, `push`, `merge`, `rebase`, `reset --hard`, `cherry-pick`, `revert`, `tag`, `stash drop` or `branch -D`. Propose commit messages with `/sdd:commit`; the user commits.',
    ruleDeps: 'Never install or add dependencies, and never edit dependency sections or lockfiles, without asking first.',
    ruleProtected: 'Changes in a protected zone stop the work: explain what and why, the alternatives, and draft an ADR. Continue only after approval. Zones:',
    ruleRetries: (n) => `At most ${n} automatic fix attempts per task, and only inside the task scope. Out of scope, protected zone or the same error twice: stop, write a triage report (error, reproduction, hypotheses, 2–3 options, recommendation) and let the user choose. Do not change code during triage.`,
    ruleVerify: 'Never report a task as done while lint, typecheck or tests fail.',
    ruleManual: (g) => `After each ${g === 'task' ? 'task' : g === 'story' ? 'user story' : 'spec'}, give manual test instructions (how to start the app, URL or command, steps, test data, expected result per requirement) and wait for the user's OK or KO.`,
    ruleDocs: 'Only create documentation files (`.md`, `.mdx`) in:',
    ruleLanes: 'Each role writes only in its own paths (see Roles).',
    ruleHarness: 'Never edit `harness.config.yaml`, `.harness/` or files generated by the harness.',
    components: 'Components',
    compHeader: '| Component | Path | Stack | Spec prefix | Implemented by | Verification |',
    notConfigured: 'not configured: ask the user before the first task',
    roles: 'Roles',
    readOnly: 'read-only',
    conventions: 'Conventions',
    languages: (l) => `Languages: code ${l.code ?? '?'}, specs ${l.specs ?? '?'}, docs ${l.docs ?? '?'}, commits ${l.commits ?? '?'}, UI ${l.ui ?? '?'}.`,
    commitStyle: (c, note) => (c === 'custom' ? `Commit messages: follow the project convention${note ? ` in \`${note}\`` : ''}.` : c === 'gitmoji' ? 'Commit messages: gitmoji.' : 'Commit messages: Conventional Commits.'),
    style: (s) => `Style and tooling: ${s.join(', ')}.`,
    readBefore: (file, dir) => `Before working in \`${dir}\`, read \`${file}\`.`,
    compTitle: (id) => `Component \`${id}\``,
    compOwner: (role) => `Implemented by: \`${role}\`. Other roles only read here, except \`qa-tester\` in test files.`,
    compPrefix: (p) => `Spec IDs: \`${p}-NNN\`.`,
    compVerify: 'Verification (run from this directory):',
    compStack: (s) => `Stack: ${s || 'not detected'}.`,
  },
  es: {
    note: 'Generado por sdd-harness. No edites este bloque: cambia harness.config.yaml y ejecuta `sdd-harness sync`.',
    title: 'Spec-Driven Development (sdd-harness)',
    precedence: 'Precedencia',
    precedenceText: (sources) => `Si las instrucciones chocan, sigue este orden: 1) \`docs/constitution.md\`; 2) convenciones del proyecto: el resto de este archivo${sources.length ? ` y ${sources.map((s) => `\`${s}\``).join(', ')}` : ''}; 3) skills del harness; 4) skills de terceros.`,
    workflow: 'Flujo',
    workflowText: 'Constitución → spec → clarificación → plan → tareas → implementación (una tarea cada vez, tests primero) → validación → cambio (primero la spec, luego el código). Nunca pases a la fase siguiente sin la aprobación explícita del usuario. Plantillas: `.harness/templates/`.',
    commands: 'Comandos: `/sdd:constitution`, `/sdd:spec`, `/sdd:clarify`, `/sdd:plan`, `/sdd:tasks`, `/sdd:next`, `/sdd:validate`, `/sdd:change`, `/sdd:status`, `/sdd:commit` (`sdd-harness doctor` muestra la sintaxis de cada herramienta).',
    rules: 'Reglas innegociables',
    ruleCommit: 'Nunca ejecutes `git commit`, `push`, `merge`, `rebase`, `reset --hard`, `cherry-pick`, `revert`, `tag`, `stash drop` ni `branch -D`. Propón los mensajes con `/sdd:commit`; el commit lo hace el usuario.',
    ruleDeps: 'Nunca instales ni añadas dependencias, ni edites secciones de dependencias o lockfiles, sin preguntar antes.',
    ruleProtected: 'Un cambio en una zona protegida detiene el trabajo: explica qué y por qué, las alternativas, y redacta un borrador de ADR. Sigue solo tras la aprobación. Zonas:',
    ruleRetries: (n) => `Como máximo ${n} intentos automáticos de corrección por tarea, y solo dentro de su alcance. Fuera de alcance, zona protegida o el mismo error dos veces: detente, escribe un informe de triage (error, reproducción, hipótesis, 2–3 opciones, recomendación) y deja que el usuario elija. No cambies código durante el triage.`,
    ruleVerify: 'Nunca des una tarea por terminada con lint, tipos o tests fallando.',
    ruleManual: (g) => `Tras cada ${g === 'task' ? 'tarea' : g === 'story' ? 'historia' : 'spec'}, da instrucciones de prueba manual (cómo arrancar la app, URL o comando, pasos, datos de prueba y resultado esperado por requisito) y espera el OK o KO del usuario.`,
    ruleDocs: 'Crea archivos de documentación (`.md`, `.mdx`) solo en:',
    ruleLanes: 'Cada rol escribe solo en sus rutas (ver Roles).',
    ruleHarness: 'Nunca edites `harness.config.yaml`, `.harness/` ni los archivos generados por el harness.',
    components: 'Componentes',
    compHeader: '| Componente | Ruta | Stack | Prefijo de spec | Lo implementa | Verificación |',
    notConfigured: 'sin configurar: pregunta al usuario antes de la primera tarea',
    roles: 'Roles',
    readOnly: 'solo lectura',
    conventions: 'Convenciones',
    languages: (l) => `Idiomas: código ${l.code ?? '?'}, specs ${l.specs ?? '?'}, docs ${l.docs ?? '?'}, commits ${l.commits ?? '?'}, interfaz ${l.ui ?? '?'}.`,
    commitStyle: (c, note) => (c === 'custom' ? `Mensajes de commit: sigue la convención del proyecto${note ? ` en \`${note}\`` : ''}.` : c === 'gitmoji' ? 'Mensajes de commit: gitmoji.' : 'Mensajes de commit: Conventional Commits.'),
    style: (s) => `Estilo y herramientas: ${s.join(', ')}.`,
    readBefore: (file, dir) => `Antes de trabajar en \`${dir}\`, lee \`${file}\`.`,
    compTitle: (id) => `Componente \`${id}\``,
    compOwner: (role) => `Lo implementa: \`${role}\`. El resto de roles solo lee aquí, salvo \`qa-tester\` en los archivos de test.`,
    compPrefix: (p) => `IDs de spec: \`${p}-NNN\`.`,
    compVerify: 'Verificación (ejecutar desde este directorio):',
    compStack: (s) => `Stack: ${s || 'no detectado'}.`,
  },
};

export function contextStrings(lang) {
  return L[lang] ?? L.en;
}

function verifyCell(v, t) {
  const cmds = ['lint', 'typecheck', 'test', 'e2e'].filter((k) => v?.[k]).map((k) => `${k}: \`${v[k]}\``);
  return cmds.length ? cmds.join('<br>') : t.notConfigured;
}

/**
 * @param {object} config
 * @param {{ componentFiles: Record<string, string | null> }} ctx  where each
 *   component's context lives (null when it is covered by the root file)
 */
export function rootContext(config, ctx) {
  const lang = config.language?.docs ?? 'en';
  const t = contextStrings(lang);
  const whitelist = config.docs_whitelist ?? [...DEFAULT_DOCS_WHITELIST];
  const protectedZones = Object.entries(config.protected ?? {}).filter(([, globs]) => globs?.length);
  const comps = Object.entries(config.components ?? {});
  const out = [
    `<!-- ${t.note} -->`,
    `# ${t.title}`,
    '',
    `## ${t.precedence}`,
    '',
    t.precedenceText(config.conventions?.sources ?? []),
    '',
    `## ${t.workflow}`,
    '',
    t.workflowText,
    '',
    t.commands,
    '',
    `## ${t.rules}`,
    '',
    `- ${t.ruleCommit}`,
    `- ${t.ruleDeps}`,
    `- ${t.ruleProtected}`,
    ...protectedZones.map(([name, globs]) => `  - ${name}: ${globs.map((g) => `\`${g}\``).join(', ')}`),
    `- ${t.ruleRetries(config.retries?.in_scope ?? 2)}`,
    `- ${t.ruleVerify}`,
    `- ${t.ruleManual(config.gates?.manual_test ?? 'task')}`,
    `- ${t.ruleDocs} ${whitelist.map((w) => `\`${w}\``).join(', ')}.`,
    `- ${t.ruleLanes}`,
    `- ${t.ruleHarness}`,
    '',
    `## ${t.components}`,
    '',
    t.compHeader,
    '|---|---|---|---|---|---|',
    ...comps.map(([id, c]) => `| \`${id}\` | \`${c.path}\` | ${c.stack ?? ''} | ${c.id_prefix ?? ''} | \`${implementerFor(c.kind ?? 'other')}\` | ${verifyCell(c.verify, t)} |`),
    '',
    ...comps.flatMap(([id, c]) => {
      const file = ctx.componentFiles?.[id];
      if (!file) return [];
      return [t.readBefore(file, c.path)];
    }),
    `## ${t.roles}`,
    '',
    ...neededRoles(config).map(({ role, writes }) => `- \`${role}\`: ${writes.length ? writes.map((w) => `\`${w}\``).join(', ') : t.readOnly}`),
    '',
    `## ${t.conventions}`,
    '',
    `- ${t.languages(config.language ?? {})}`,
    `- ${t.commitStyle(config.conventions?.commits, config.conventions?.commits_note)}`,
    ...(config.conventions?.style?.length ? [`- ${t.style(config.conventions.style)}`] : []),
  ];
  // Keep a blank line between the component pointers and the next heading.
  return out.join('\n').replace(/\n(## )/g, '\n\n$1').replace(/\n{3,}/g, '\n\n');
}

const STACK_HINTS = {
  en: {
    react: 'React: function components and hooks; keep components small and reuse the design system.',
    next: 'Next.js: respect the router in use (app/ or pages/); server code never reaches the client bundle.',
    vue: 'Vue: single-file components with the Composition API.',
    svelte: 'Svelte: keep components small; stores for shared state.',
    angular: 'Angular: follow the module and service structure already in place.',
    nestjs: 'NestJS: controllers stay thin; logic in services; validate input with DTOs at the edge.',
    express: 'Express: validate input at the edge; errors go through one error handler.',
    fastify: 'Fastify: declare schemas for input and output.',
    django: 'Django: migrations only through the protected-zone gate.',
    fastapi: 'FastAPI: Pydantic models at the edge; dependencies for cross-cutting concerns.',
    prisma: 'Prisma: schema and migrations are a protected zone.',
    postgres: 'PostgreSQL: parameterised queries only; schema changes through migrations.',
    ts: 'TypeScript: no `any` without a reason; the typecheck must pass.',
  },
  es: {
    react: 'React: componentes de función y hooks; componentes pequeños y reutiliza el sistema de diseño.',
    next: 'Next.js: respeta el router en uso (app/ o pages/); el código de servidor nunca llega al bundle del cliente.',
    vue: 'Vue: componentes de un solo archivo con la Composition API.',
    svelte: 'Svelte: componentes pequeños; stores para el estado compartido.',
    angular: 'Angular: sigue la estructura de módulos y servicios existente.',
    nestjs: 'NestJS: controladores finos; la lógica en servicios; valida la entrada con DTOs en el borde.',
    express: 'Express: valida la entrada en el borde; los errores pasan por un único manejador.',
    fastify: 'Fastify: declara esquemas de entrada y salida.',
    django: 'Django: las migraciones solo pasan por el gate de zona protegida.',
    fastapi: 'FastAPI: modelos Pydantic en el borde; dependencias para lo transversal.',
    prisma: 'Prisma: el esquema y las migraciones son zona protegida.',
    postgres: 'PostgreSQL: solo consultas parametrizadas; cambios de esquema mediante migraciones.',
    ts: 'TypeScript: nada de `any` sin motivo; el typecheck debe pasar.',
  },
};

/** RF-GEN-03: context of one component. */
export function componentContext(config, id) {
  const c = config.components[id];
  const lang = config.language?.docs ?? 'en';
  const t = contextStrings(lang);
  const hints = STACK_HINTS[lang] ?? STACK_HINTS.en;
  const parts = String(c.stack ?? '').toLowerCase().split(/[+\s,]+/);
  const verify = ['lint', 'typecheck', 'test', 'e2e'].filter((k) => c.verify?.[k]);
  return [
    `<!-- ${t.note} -->`,
    `# ${t.compTitle(id)}`,
    '',
    `- ${t.compStack(c.stack)}`,
    `- ${t.compOwner(implementerFor(c.kind ?? 'other'))}`,
    ...(c.id_prefix ? [`- ${t.compPrefix(c.id_prefix)}`] : []),
    '',
    t.compVerify,
    '',
    ...(verify.length ? verify.map((k) => `- ${k}: \`${c.verify[k]}\``) : [`- ${t.notConfigured}`]),
    ...(parts.some((p) => hints[p]) ? ['', ...parts.filter((p) => hints[p]).map((p) => `- ${hints[p]}`)] : []),
  ].join('\n');
}
