// Neutral core generator (RF-GEN-01..08, RF-MOD-01..05, RF-GEN-14).
//
// Produces the desired state of the project as a list of entries:
//   { kind: 'file',  path, content, generator }          file owned by the harness
//   { kind: 'block', path, content, generator, style? }  managed block
//   { kind: 'json',  path, values, appends, generator }  keys merged into a JSON file
// Tool adapters add their own entries; `finalize` runs once all are known.

import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_DOCS_WHITELIST } from '../guards/project.js';
import { findBlock } from '../engine/blocks.js';
import { toLf } from '../engine/text.js';
import { rootContext, componentContext, neededRoles } from './context.js';
import { template, TEMPLATE_LANG } from './templates.js';

export const HEADER = {
  md: '<!-- Generated by sdd-harness. Do not edit by hand: run "sdd-harness sync". -->',
  js: '// Generated by sdd-harness. Do not edit by hand: run "sdd-harness sync".',
  hash: '# Generated by sdd-harness. Do not edit by hand: run "sdd-harness sync".',
};

/** Characters each tool reads from a context file before truncating or warning (RF-GEN-14). */
export const TOOL_CONTEXT_LIMITS = { codex: 32768, 'claude-code': 40000, opencode: 40000, antigravity: 12000 };

const GUARD_SOURCES = [
  'args.js', 'checks.js', 'contracts.js', 'docs-guard.js', 'files-guard.js', 'flow.js', 'glob.js', 'hook.js', 'project.js',
  'runtime-messages.js', 'sdd.js', 'state.js', 'status.js', 'tasks.js', 'tracker-sync.js', 'verify.js',
];
const GUARDS_DIR = path.dirname(fileURLToPath(new URL('../guards/hook.js', import.meta.url)));

const ARTIFACT_EXCLUDES = ['/specs/', '/docs/constitution.md', '/docs/decisions/', '/docs/architecture/', '/docs/lessons.md'];

export function withJsHeader(source) {
  const text = toLf(source);
  if (text.startsWith('#!')) {
    const nl = text.indexOf('\n');
    return `${text.slice(0, nl + 1)}${HEADER.js}\n${text.slice(nl + 1)}`;
  }
  return `${HEADER.js}\n${text}`;
}

/**
 * Quotes every unquoted scalar of the YAML frontmatter (`key: value`) as a
 * double-quoted string. Values such as "x: y", "[scope]" or "<arg>" are not
 * valid plain YAML and stricter parsers drop the whole agent/skill.
 */
export function quoteFrontmatter(text) {
  const t = toLf(text);
  if (!t.startsWith('---\n')) return t;
  const end = t.indexOf('\n---\n', 4);
  if (end === -1) return t;
  const head = t.slice(4, end).split('\n').map((line) => {
    const m = /^([A-Za-z0-9_-]+):[ \t]+(.+)$/.exec(line);
    if (!m) return line;
    const v = m[2].trim();
    if (/^(["']).*\1$/.test(v)) return line;
    return `${m[1]}: ${JSON.stringify(v)}`;
  }).join('\n');
  return `---\n${head}${t.slice(end)}`;
}

/** GEN-07 header for markdown; after the YAML front matter when there is one. */
export function withMdHeader(text) {
  const t = quoteFrontmatter(text);
  if (t.startsWith('---\n')) {
    const end = t.indexOf('\n---\n', 4);
    if (end !== -1) return `${t.slice(0, end + 5)}${HEADER.md}\n${t.slice(end + 5)}`;
  }
  return `${HEADER.md}\n${t}`;
}

const cleanDir = (p) => String(p).replace(/\\/g, '/').replace(/^\.\/?/, '').replace(/\/$/, '');

/** Folders of the repositories in multi-repo and workspace topologies. */
export function repoDirs(config) {
  if (!['multi-repo', 'workspace'].includes(config.topology)) return [];
  return [...new Set(Object.values(config.components ?? {}).map((c) => cleanDir(c.path)).filter(Boolean))];
}

/** Repos whose own specs/ and docs/ the agents may write: only with `specs.location: per-repo`. */
export function specRepoDirs(config) {
  return config.specs?.location === 'per-repo' ? repoDirs(config) : [];
}

/** Whitelist, extended with each repo's spec and doc folders (RF-TOP-02). */
export function docsWhitelist(config) {
  const base = config.docs_whitelist ?? [...DEFAULT_DOCS_WHITELIST];
  const anchored = base.filter((g) => /^(specs|docs)\//.test(g));
  return [...new Set([...base, ...specRepoDirs(config).flatMap((dir) => anchored.map((g) => `${dir}/${g}`))])];
}

/** Protected zones the guards enforce, including the harness itself (RF-GAT-09). */
export function guardProtected(config, generatedPaths, blockPaths = []) {
  // Files with a managed block (AGENTS.md, CLAUDE.md) stay writable outside the block.
  generatedPaths = generatedPaths.filter((p) => !blockPaths.includes(p));
  return {
    ...(config.protected ?? {}),
    harness: ['harness.config.yaml', '.harness/**', ...generatedPaths.filter((p) => !p.startsWith('.harness/') && !p.startsWith('.git/'))],
  };
}

/**
 * @param {object} config validated harness.config.yaml
 * @param {{ tracked: Set<string>, skills?: Record<string, string> }} env
 * @returns {{ entries: object[], notices: object[], agentsPath: string }}
 */
export function generateCore(config, env) {
  const local = (config.install_mode ?? 'local') === 'local';
  const tools = config.tools ?? [];
  const tracked = env.tracked ?? new Set();
  const lockedInLocal = (p) => local && tracked.has(p);
  const entries = [];
  const notices = [];
  const add = (entry) => entries.push({ generator: 'core', ...entry });

  // Component contexts first: the root context points to them.
  const componentFiles = {};
  for (const [id, c] of Object.entries(config.components ?? {})) {
    const dir = String(c.path).replace(/\\/g, '/').replace(/^\.\/?/, '').replace(/\/$/, '');
    if (!dir) {
      componentFiles[id] = null;
      continue;
    }
    const target = `${dir}/AGENTS.md`;
    const content = componentContext(config, id);
    if (lockedInLocal(target)) {
      const fallback = `.harness/context/${id}.md`;
      add({ kind: 'file', path: fallback, content: `${HEADER.md}\n${content}\n` });
      componentFiles[id] = fallback;
    } else {
      add({ kind: 'block', path: target, content });
      componentFiles[id] = target;
    }
  }
  const root = rootContext(config, { componentFiles });

  // Root context (RF-GEN-01) and its channel per tool (RF-GEN-02, RF-MOD-03/04).
  let agentsPath = 'AGENTS.md';
  if (lockedInLocal('AGENTS.md')) {
    agentsPath = '.harness/context/AGENTS.md';
    add({ kind: 'file', path: agentsPath, content: `${HEADER.md}\n${root}\n` });
    for (const tool of tools.filter((x) => x !== 'claude-code')) {
      notices.push({ code: 'toolNeedsTeam', params: { tool, file: 'AGENTS.md' } });
    }
  } else {
    add({ kind: 'block', path: 'AGENTS.md', content: root });
  }
  if (tools.includes('claude-code')) {
    const claudeFile = local ? 'CLAUDE.local.md' : 'CLAUDE.md';
    if (lockedInLocal(claudeFile)) notices.push({ code: 'toolNeedsTeam', params: { tool: 'claude-code', file: claudeFile } });
    else add({ kind: 'block', path: claudeFile, content: `@${agentsPath}` });
  }

  // Templates in the configured languages (RF-CNV-04).
  for (const [name, which] of Object.entries(TEMPLATE_LANG)) {
    const lang = config.language?.[which] ?? 'en';
    add({ kind: 'file', path: `.harness/templates/${name}.md`, content: `${HEADER.md}\n${template(name, lang)}` });
  }

  // Guards and flow scripts, copied without dependencies so hooks run them with plain Node.
  for (const source of GUARD_SOURCES) {
    const [from, to] = Array.isArray(source) ? source : [source, source];
    add({ kind: 'file', path: `.harness/scripts/${to}`, content: withJsHeader(readFileSync(path.join(GUARDS_DIR, from), 'utf8')) });
  }
  // The copied scripts are ES modules whatever Node.js version runs them.
  add({ kind: 'file', path: '.harness/scripts/package.json', content: '{\n  "type": "module"\n}\n' });

  // Canonical skills (RF-GEN-05); tools that need other paths get copies (RF-GEN-06).
  for (const [name, content] of Object.entries(env.skills ?? {})) {
    add({ kind: 'file', path: `.agents/skills/${name}/SKILL.md`, content: withMdHeader(content) });
  }

  // RF-TOP-03: the workspace lists its repositories outside any of them.
  if (config.topology === 'workspace') {
    const list = repoDirs(config).map((dir) => `  - ${dir}`).join('\n');
    add({ kind: 'file', path: 'harness.workspace.yaml', content: `${HEADER.hash}\nrepos:\n${list}\n` });
  }

  // State and logs never go to version control (RF-OBS-05).
  if (!local) add({ kind: 'file', path: '.harness/.gitignore', content: `${HEADER.hash}\nstate/\nlogs/\n` });

  return { entries, notices, agentsPath };
}

/**
 * Last step, once every generator contributed: guard settings,
 * .git/info/exclude and the context size check.
 * @param {{ excludePath: string | null, read: (p: string) => string | null }} env
 */
export function finalize(config, env, { entries, notices, agentsPath }) {
  const local = (config.install_mode ?? 'local') === 'local';
  const tools = config.tools ?? [];
  const add = (entry) => entries.push({ generator: 'core', ...entry });

  const generatedPaths = [...new Set(entries.map((e) => e.path))];
  const contextBlocks = [...new Set(entries.filter((e) => e.kind === 'block' && e.style !== 'hash').map((e) => e.path))];
  add({
    kind: 'file',
    path: '.harness/guards.json',
    content: JSON.stringify(
      {
        language: config.cli?.language ?? config.language?.docs ?? 'en',
        docs_mode: config.gates?.docs ?? 'free',
        docs_whitelist: docsWhitelist(config),
        specs: { location: config.specs?.location ?? 'root', id_prefix: config.specs?.id_prefix ?? 'SPEC' },
        protected: guardProtected(config, generatedPaths, contextBlocks),
        managed_blocks: contextBlocks,
        retries: { in_scope: config.retries?.in_scope ?? 2, protected: config.retries?.protected ?? 0 },
        components: Object.fromEntries(Object.entries(config.components ?? {}).map(([id, c]) => [id, { path: c.path, kind: c.kind ?? 'other', id_prefix: c.id_prefix, verify: c.verify ?? {} }])),
        roles: Object.fromEntries(neededRoles(config).map((r) => [r.role, { writes: r.writes }])),
        manual_test: config.gates?.manual_test ?? 'story',
        specs_language: config.language?.specs ?? 'en',
        docs_language: config.language?.docs ?? 'en',
        commits: { convention: config.conventions?.commits ?? 'conventional', language: config.language?.commits ?? 'en', note: config.conventions?.commits_note },
        topology: config.topology,
        tracker: config.tracker?.enabled && config.tracker.provider ? { provider: config.tracker.provider, project: config.tracker.project ?? null, repo: config.tracker.repo ?? null } : null,
      },
      null,
      2,
    ) + '\n',
  });

  // .git/info/exclude of every repository (RF-MOD-01, RF-TOP-02) and local artifacts (RF-INI-10).
  const repos = env.repos ?? (env.excludePath ? [{ dir: '', excludePath: env.excludePath }] : []);
  const byRepo = new Map(repos.map((r) => [r.dir, []]));
  const repoFor = (p) => repos
    .filter((r) => r.dir === '' || p === r.dir || p.startsWith(`${r.dir}/`))
    .sort((a, b) => b.dir.length - a.dir.length)[0];
  const exclude = (p) => {
    const repo = repoFor(p);
    if (repo) byRepo.get(repo.dir).push(`/${repo.dir ? p.slice(repo.dir.length + 1) : p}`);
  };
  if (local) {
    exclude('harness.config.yaml');
    exclude('.harness/');
    // Third-party skills installed from the registry (RF-SKL-09).
    for (const s of env.installedSkills ?? []) {
      exclude(`.agents/skills/${s.name}/`);
      exclude(`.claude/skills/${s.name}/`);
    }
    for (const e of entries) if (!e.path.startsWith('.harness/') && !/(^|\/)\.git\//.test(e.path)) exclude(e.path);
  }
  if (config.artifacts?.versioned === false) for (const r of repos) byRepo.get(r.dir).push(...ARTIFACT_EXCLUDES);
  for (const r of repos) {
    const lines = [...new Set(byRepo.get(r.dir))];
    if (lines.length) add({ kind: 'block', style: 'hash', path: r.excludePath, content: lines.join('\n') });
  }
  if (local && !repos.length) notices.push({ code: 'noGitExclude', params: {} });

  // RF-GEN-14 and edge case 6: context size per tool.
  const agentsEntry = entries.find((e) => e.path === agentsPath);
  const existing = env.read?.(agentsPath) ?? null;
  const outside = existing && findBlock(existing).status === 'ok'
    ? toLf(existing).replace(/<!-- harness:begin -->[\s\S]*<!-- harness:end -->/, '')
    : existing ?? '';
  const size = outside.length + agentsEntry.content.length + 50;
  for (const tool of tools) {
    const limit = TOOL_CONTEXT_LIMITS[tool];
    if (limit && size > limit) notices.push({ code: 'contextTooLarge', params: { file: agentsPath, size, limit, tool, own: agentsEntry.content.length } });
  }
  return { entries, notices };
}
