import { neededRoles } from '../context.js';
import { withMdHeader, quoteFrontmatter } from '../core.js';

export const id = 'antigravity';
export const RULES = ['commits', 'deps', 'protected', 'docs', 'verify', 'lanes'];

const S = 'node .harness/scripts/sdd.js';

// Workflows we generate for slash commands / shortcuts
const WORKFLOWS = {
  status: ['What happened and what comes next', `Run \`${S} status\` and summarise it for the user: the spec in progress and its state, the last tasks closed, what is pending and what can start now, tasks added during implementation, the last verification and the last commits. Suggest the next step in one line.`],
  spec: ['Start a new spec', `Ask the user for a short description if they didn't provide one. Load the sdd skill and start a new spec.`],
  next: ['Launch the tasks that can start now', `Load the sdd skill and follow "Implement": \`${S} next\` lists the tasks that can start now (one per component, 2 at most); delegate them using invoke_subagent. Never more than 2 subagents working at once.`],
  docs: ['Bring the documentation up to date, in the background', `Delegate to the doc-writer subagent using invoke_subagent: update every document affected by the recent changes (git diff). Keep working on anything else meanwhile, and summarise what it updated.`],
  review: ['Review the recent changes', `Delegate at the same time to the reviewer subagent (spec compliance, quality, security) and, when there are tests to add, to qa-tester using invoke_subagent (never more than 2 subagents working at once), over the recent changes (git diff). Summarise the findings, most important first, and fix the clear ones inside the task.`],
  validate: ['Validate the spec requirement by requirement', `Run \`${S} verify\` and \`${S} validate\`. Give, for each requirement: the test that covers it and its result; requirements without a test are "not covered". End with a verdict.`],
  commit: ['Propose the commit now', `Run \`${S} commit-context\`. Propose one commit message per repository with changes, following its convention and language, referencing specs and tasks, and ask the user. If they say yes, run git add and git commit. Never push unless they ask.`],
};

function workflowFile(name, description, body) {
  return quoteFrontmatter(`---
description: ${description}
---
<!-- Generated by sdd-harness. Do not edit by hand: run "sdd-harness sync". -->

${body}
`);
}

const hook = (event) => ({ type: 'command', command: `node .harness/scripts/hook.js ${event}` });

export function generate(config, ctx) {
  const entries = [];
  const notices = [];
  const add = (e) => entries.push({ generator: id, tool: id, ...e });

  for (const [name, content] of Object.entries(ctx.skills ?? {})) {
    add({ kind: 'file', path: `.agents/skills/${name}/SKILL.md`, content: withMdHeader(content) });
  }

  for (const [name, [description, body]] of Object.entries(WORKFLOWS)) {
    add({ kind: 'file', path: `.agents/workflows/sdd-${name}.md`, content: workflowFile(name, description, body) });
  }

  add({
    kind: 'json',
    path: '.agents/hooks.json',
    values: {},
    appends: {
      'sdd-guards.PreToolUse': [
        { matcher: 'run_command|write_to_file|replace_file_content|invoke_subagent', hooks: [hook('PreToolUse')] }
      ],
      'sdd-guards.PostToolUse': [
        { matcher: 'write_to_file|replace_file_content|invoke_subagent', hooks: [hook('PostToolUse')] }
      ],
      'sdd-guards.PreInvocation': [
        { hooks: [hook('PreInvocation')] }
      ],
      'sdd-guards.UserPromptSubmit': [
        { hooks: [hook('UserPromptSubmit')] }
      ],
      'sdd-guards.SessionStart': [
        { hooks: [hook('SessionStart')] }
      ],
      'sdd-guards.Stop': [
        { hooks: [hook('Stop')] }
      ]
    },
    enforces: RULES
  });

  return { entries, notices };
}
